# Generated by Django 3.1.4 on 2021-01-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210119_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_created=True)),
                ('comment_author', models.CharField(max_length=50, verbose_name='Имя')),
                ('comment_content', models.CharField(max_length=250, verbose_name='Коммент')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Коммент', to='article.article', verbose_name='Статья')),
            ],
        ),
    ]
